### ISSUE TITLE
Структура проекта

### ISSUE THREAD

**Issue by RinatValiullov** [adelinadev/portfolio#1]
Приведи в порядок структуру проекта. Разложи файлы по соответствующим папкам. Примеры можешь посмотреть в этих шаблонах и статьях:

- [HTML5 Boilerplate](https://github.com/h5bp/html5-boilerplate)
- [Dealing with files](https://developer.mozilla.org/en-US/docs/Learn/Getting_started_with_the_web/Dealing_with_files)
- [Folder Structure for Web Development](https://medium.com/@nmayurashok/file-and-folder-structure-for-web-development-8c5c83810a5)
- [gulp-maxgraph](https://github.com/maxdenaro/gulp-maxgraph)
- [Starting template is a front-end HTML5/SCSS/JS template](https://github.com/YauhenKavalchuk/Starting_template)
- [Стартовый шаблон автора канала FrontCoder](https://github.com/FARCER/gulp4-for-frontend)
- [OptimizedHTML - Start HTML Template](https://github.com/agragregra/optimizedhtml-start-template)

и так далее...

**Comment by adelinadev** [comment]
done
